# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: nbvt-skeleton
description: NBvT Microsite Skeleton
author:
  name: NBvT
  email: daniel@studiofonkel.nl

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: pretty
paginate: 10
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

collections:
  pages:
    output: true
    permalink: /:path/
  blogs:
    output: true
    permalink: /:path/
  news:
    output: true
    permalink: /nieuws/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      active_menu: none
      layout: page
      footer: true
  - scope:
      path: ""
      type: blogs
    values:
      layout: blog
      collection: blogs
      footer: true
  - scope:
      path: ""
      type: news
    values:
      layout: news_item
      collection: news
      footer: true