# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: nbvt-skeleton
description: NBvT Microsite Skeleton
author:
  name: NBvT
  email: daniel@studiofonkel.nl

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: pretty

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

collections:
  pages:
    permalink: /:path/
    output: true
  blogs:
    output: true
    permalink: /blogs/:path/
    paginate: true
    paginate_path: blogs
    paginate_count: 3

  news:
    output: true
    permalink: /nieuws/:path/
    paginate: true
    paginate_path: nieuws
    paginate_count: 3

defaults:
  - scope:
      path: ""
      type: pages
    values:
      active_menu: none
      layout: page
      footer: true
      collection: pages
  - scope:
      path: ""
      type: blogs
    values:
      layout: blog
      collection: blogs
      footer: true
  - scope:
      path: ""
      type: news
    values:
      layout: news_item
      collection: news
      footer: true
